import { Link } from 'react-router-dom'
import { cn } from '@/lib/utils'
import { buttonVariants } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import {
    Table,
    TableHeader,
    TableBody,
    TableHead,
    TableRow,
    TableCell,
} from '@/components/ui/table'
import { ArrowLeft, Trophy } from 'lucide-react'
import {
    BarChart,
    Bar,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    Legend,
    ResponsiveContainer,
} from 'recharts'
import { employeePerformance, formatCurrency } from '../data/mock-reports'

const rankColors = ['bg-yellow-100 text-yellow-700', 'bg-gray-100 text-gray-700', 'bg-orange-100 text-orange-700']

export default function EmployeeReportPage() {
    const sorted = [...employeePerformance].sort((a, b) => b.revenueGenerated - a.revenueGenerated)
    const totalRevenue = sorted.reduce((s, e) => s + e.revenueGenerated, 0)
    const totalClosed = sorted.reduce((s, e) => s + e.casesClosed, 0)

    return (
        <div className="space-y-6">
            <div className="flex items-center gap-3">
                <Link to="/reports" className={cn(buttonVariants({ variant: 'ghost', size: 'icon-sm' }))}>
                    <ArrowLeft className="size-4" />
                </Link>
                <div>
                    <h1 className="text-2xl font-bold">Employee Performance</h1>
                    <p className="text-sm text-muted-foreground">Team rankings & output</p>
                </div>
            </div>

            {/* Summary */}
            <div className="grid gap-3 sm:grid-cols-3">
                <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Team Size</p><p className="text-lg font-bold">{sorted.length}</p></CardContent></Card>
                <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Total Cases Closed</p><p className="text-lg font-bold">{totalClosed}</p></CardContent></Card>
                <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Total Revenue</p><p className="text-lg font-bold text-green-600">{formatCurrency(totalRevenue)}</p></CardContent></Card>
            </div>

            {/* Top 3 performers */}
            <div className="grid gap-3 sm:grid-cols-3">
                {sorted.slice(0, 3).map((emp, i) => (
                    <Card key={emp.name} className="relative overflow-hidden">
                        <CardContent className="p-4 flex items-center gap-3">
                            <div className={cn('rounded-full p-2', i === 0 ? 'bg-yellow-100' : i === 1 ? 'bg-gray-100' : 'bg-orange-100')}>
                                <Trophy className={cn('size-4', i === 0 ? 'text-yellow-600' : i === 1 ? 'text-gray-600' : 'text-orange-600')} />
                            </div>
                            <div>
                                <p className="font-semibold">{emp.name}</p>
                                <p className="text-xs text-muted-foreground">{emp.role}</p>
                                <p className="text-sm font-medium text-green-600 mt-0.5">{formatCurrency(emp.revenueGenerated)}</p>
                            </div>
                            <Badge className={cn('absolute top-2 right-2 text-xs', rankColors[i] ?? '')}>
                                #{i + 1}
                            </Badge>
                        </CardContent>
                    </Card>
                ))}
            </div>

            {/* Revenue chart */}
            <Card>
                <CardContent className="p-4">
                    <p className="text-sm font-medium mb-3">Revenue Generated by Employee</p>
                    <ResponsiveContainer width="100%" height={300}>
                        <BarChart data={sorted} layout="vertical">
                            <CartesianGrid strokeDasharray="3 3" />
                            <XAxis type="number" tick={{ fontSize: 11 }} tickFormatter={(v) => `₹${(v / 1000).toFixed(0)}K`} />
                            <YAxis type="category" dataKey="name" tick={{ fontSize: 12 }} width={120} />
                            <Tooltip formatter={(v) => formatCurrency(Number(v))} />
                            <Bar dataKey="revenueGenerated" name="Revenue" fill="#10b981" radius={[0, 4, 4, 0]} />
                        </BarChart>
                    </ResponsiveContainer>
                </CardContent>
            </Card>

            {/* Cases chart */}
            <Card>
                <CardContent className="p-4">
                    <p className="text-sm font-medium mb-3">Cases & Leads</p>
                    <ResponsiveContainer width="100%" height={280}>
                        <BarChart data={sorted}>
                            <CartesianGrid strokeDasharray="3 3" />
                            <XAxis dataKey="name" tick={{ fontSize: 11 }} />
                            <YAxis tick={{ fontSize: 11 }} />
                            <Tooltip />
                            <Legend />
                            <Bar dataKey="leadsHandled" name="Leads Handled" fill="#3b82f6" radius={[4, 4, 0, 0]} />
                            <Bar dataKey="casesClosed" name="Cases Closed" fill="#10b981" radius={[4, 4, 0, 0]} />
                            <Bar dataKey="activeCases" name="Active Cases" fill="#f59e0b" radius={[4, 4, 0, 0]} />
                        </BarChart>
                    </ResponsiveContainer>
                </CardContent>
            </Card>

            {/* Full table */}
            <div className="rounded-lg border">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Rank</TableHead>
                            <TableHead>Employee</TableHead>
                            <TableHead className="hidden sm:table-cell">Role</TableHead>
                            <TableHead>Leads</TableHead>
                            <TableHead>Closed</TableHead>
                            <TableHead>Active</TableHead>
                            <TableHead>Revenue</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {sorted.map((emp, i) => (
                            <TableRow key={emp.name}>
                                <TableCell>
                                    <Badge className={cn('text-xs', i < 3 ? rankColors[i] : 'bg-muted text-muted-foreground')}>
                                        #{i + 1}
                                    </Badge>
                                </TableCell>
                                <TableCell className="font-medium">{emp.name}</TableCell>
                                <TableCell className="hidden sm:table-cell">{emp.role}</TableCell>
                                <TableCell>{emp.leadsHandled}</TableCell>
                                <TableCell>{emp.casesClosed}</TableCell>
                                <TableCell>{emp.activeCases}</TableCell>
                                <TableCell className="font-medium text-green-600">{formatCurrency(emp.revenueGenerated)}</TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </div>
        </div>
    )
}
